# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'foodie' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftFortuneWheel'

  # Pods for foodie

  target 'foodieTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'foodieUITests' do
    # Pods for testing
  end

end
